name: torch_rgcn_venv
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy=1.16.4
  - pandas=1.0.5
  - pip=19.2.2
  - python=3.7.4
  - pyyaml=5.3.1
  - scikit-learn=0.21.2
  - yaml=0.1.7
  - pip:
    - dnspython==1.16.0
    - pymongo==3.10.1
    - pytest==5.3.1
    - rdflib==4.2.2
    - sacred==0.8.1
    - scipy==1.3.1
    - torch==1.3.1
    - tqdm==4.35.0
